### ISSUE TITLE
input S/D/R

### ISSUE THREAD

**Issue by jpesicek** [timofeevda/seismic-beachballs-demo#1]
Hi Denis,
If you would accept a feature request:

I would like the option to input strike, dip, and rake as an alternative to the MT components.  For teaching, it is nice to see how these more intuitive values translate to MT values, and to easily view pure double-couple events in 3D.

Also, is it easy to add the upper hemisphere view as an option? That would also be informative for students.

thanks so much for your work on this, it is exactly what I wanted for teaching.
Best regards,
Jeremy

**Comment by timofeevda** [comment]
Yep, the first version had an option to input SDR values. The same with upper hemisphere. I'll try to find time and get it back.
